### ISSUE TITLE
Make It Faster

### ISSUE THREAD

**Issue by phish7381** [TrollsterCooleg/Nuker#1]
you can use something like this to make it faster https://github.com/phishontop/sockets-wrapper

**Comment by TrollsterCooleg** [comment]
Maybe I would if it wasn't in a completely different coding language and I actually cared about nuking servers. The nice thing is that I actually don't care about making it faster because I don't really have any plans to nuke any servers. Oh and also discord has ratelimits. The nuker is fast enough to do damage anyways, but it's not really meant to be a good nuker, it was just a random project out of boredom.
